meta_product_name: "Cabinet de Psychologie clinique - Caen"
meta_title: "Cabinet de Psychologie clinique - Caen"
meta_description: "Ce site est consacré à notre activité de psychologue et a pour ambition de parler des questions que l'on se pose avant de consulter un professionnel ou simplement d’alimenter votre curiosité en la matière."
meta_image: "cover.png" # should exist in `app/assets/images/`
